// Copyright 2023-2024 Mikael Lund
//
// Licensed under the Apache license, version 2.0 (the "license");
// you may not use this file except in compliance with the license.
// You may obtain a copy of the license at
//
//     http://www.apache.org/licenses/license-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the license is distributed on an "as is" basis,
// without warranties or conditions of any kind, either express or implied.
// See the license for the specific language governing permissions and
// limitations under the license.

//! X-PLOR PSF (Protein Structure File) writer.
//!
//! Writes topology (atoms, bonds, angles, dihedrals) in
//! [NAMD/X-PLOR extended format](https://www.ks.uiuc.edu/Training/Tutorials/namd/namd-tutorial-unix-html/node23.html)
//! for use with VMD and other visualization tools.
//! Despite the name, the format is not protein-specific and works for
//! arbitrary particle systems (colloids, coarse-grained models, etc.).

use crate::group::Group;
use crate::topology::{IndexRange, Topology};
use anyhow::Context;
use std::io::{BufWriter, Write};
use std::path::Path;

/// Write a PSF file from the current topology and group layout.
pub fn write_psf(path: &Path, topology: &Topology, groups: &[Group]) -> anyhow::Result<()> {
    let file = std::fs::File::create(path)
        .with_context(|| format!("Cannot create '{}'", path.display()))?;
    let mut w = BufWriter::new(file);

    writeln!(w, "PSF EXT")?;
    writeln!(w)?;
    writeln!(w, "{:>10} !NTITLE", 1)?;
    writeln!(w, " REMARKS generated by Faunus")?;
    writeln!(w)?;

    let total_atoms: usize = groups.iter().map(|g| g.len()).sum();
    write_atoms(&mut w, topology, groups, total_atoms)?;
    write_bonded_sections(&mut w, topology, groups)?;

    // Empty sections
    for tag in ["!NIMPHI: impropers", "!NDON: donors", "!NACC: acceptors"] {
        writeln!(w, "{:>10} {tag}", 0)?;
        writeln!(w)?;
    }

    Ok(())
}

/// Write the !NATOM section directly to the writer (no intermediate Vec).
fn write_atoms(
    w: &mut impl Write,
    topology: &Topology,
    groups: &[Group],
    total_atoms: usize,
) -> anyhow::Result<()> {
    writeln!(w, "{:>10} !NATOM", total_atoms)?;

    let atomkinds = topology.atomkinds();
    let mut atom_index = 0usize;
    let mut resid_counter = 0usize;

    for group in groups {
        let mol = &topology.moleculekinds()[group.molecule()];
        let mut residue_cursor = 0usize;

        // Increment resid once per group when no residues are defined
        if mol.residues().is_empty() {
            resid_counter += 1;
        }

        for (i, &atom_idx) in mol.atom_indices().iter().enumerate() {
            atom_index += 1;
            let atom_kind = &atomkinds[atom_idx];
            let atom_name = mol.resolved_atom_name(i, atomkinds);
            let (resname, resid) =
                resolve_residue(mol, i, &mut residue_cursor, &mut resid_counter);

            // CHARMM EXT format: (I10,1X,A8,1X,A8,1X,A8,1X,A8,1X,A4,1X,2G14.6,I8)
            writeln!(
                w,
                "{:>10} {:<8.8} {:<8} {:<8.8} {:<8.8} {:<4.4} {:>14.6} {:>14.4} {:>8}",
                atom_index,
                mol.name(),
                resid,
                resname,
                atom_name,
                atom_kind.name(),
                atom_kind.charge(),
                atom_kind.mass(),
                0,
            )?;
        }
    }
    writeln!(w)?;
    Ok(())
}

/// Resolve residue name and id using a cursor to avoid repeated linear scans.
fn resolve_residue<'a>(
    mol: &'a crate::topology::MoleculeKind,
    atom_index: usize,
    cursor: &mut usize,
    counter: &mut usize,
) -> (&'a str, usize) {
    let residues = mol.residues();
    // Advance cursor past residues that end before this atom
    while *cursor < residues.len() && residues[*cursor].range().end <= atom_index {
        *cursor += 1;
    }
    if *cursor < residues.len() && residues[*cursor].range().contains(&atom_index) {
        let res = &residues[*cursor];
        let resid = res.number().unwrap_or(*counter);
        return (res.name(), resid);
    }
    // No residue defined — use molecule name; resid set per-group by caller
    (mol.name(), *counter)
}

/// Write all bonded sections (!NBOND, !NTHETA, !NPHI).
fn write_bonded_sections(
    w: &mut impl Write,
    topology: &Topology,
    groups: &[Group],
) -> anyhow::Result<()> {
    // Pre-compute counts for section headers
    let (n_bonds, n_angles, n_dihedrals) = groups.iter().fold((0, 0, 0), |(b, a, d), g| {
        let mol = &topology.moleculekinds()[g.molecule()];
        (
            b + mol.bonds().len(),
            a + mol.torsions().len(),
            d + mol.dihedrals().len(),
        )
    });

    // Bonds (4 pairs per line)
    writeln!(w, "{:>10} !NBOND: bonds", n_bonds)?;
    let mut col = 0;
    for group in groups {
        let mol = &topology.moleculekinds()[group.molecule()];
        let offset = group.start() + 1;
        for bond in mol.bonds() {
            let idx = bond.index();
            write!(w, "{:>10}{:>10}", idx[0] + offset, idx[1] + offset)?;
            col += 1;
            if col % 4 == 0 {
                writeln!(w)?;
            }
        }
    }
    if n_bonds > 0 && col % 4 != 0 {
        writeln!(w)?;
    }
    writeln!(w)?;

    // Angles (3 triplets per line)
    writeln!(w, "{:>10} !NTHETA: angles", n_angles)?;
    col = 0;
    for group in groups {
        let mol = &topology.moleculekinds()[group.molecule()];
        let offset = group.start() + 1;
        for torsion in mol.torsions() {
            let idx = torsion.index();
            write!(
                w,
                "{:>10}{:>10}{:>10}",
                idx[0] + offset,
                idx[1] + offset,
                idx[2] + offset
            )?;
            col += 1;
            if col % 3 == 0 {
                writeln!(w)?;
            }
        }
    }
    if n_angles > 0 && col % 3 != 0 {
        writeln!(w)?;
    }
    writeln!(w)?;

    // Dihedrals (2 quadruplets per line)
    writeln!(w, "{:>10} !NPHI: dihedrals", n_dihedrals)?;
    col = 0;
    for group in groups {
        let mol = &topology.moleculekinds()[group.molecule()];
        let offset = group.start() + 1;
        for dihedral in mol.dihedrals() {
            let idx = dihedral.index();
            write!(
                w,
                "{:>10}{:>10}{:>10}{:>10}",
                idx[0] + offset,
                idx[1] + offset,
                idx[2] + offset,
                idx[3] + offset
            )?;
            col += 1;
            if col % 2 == 0 {
                writeln!(w)?;
            }
        }
    }
    if n_dihedrals > 0 && col % 2 != 0 {
        writeln!(w)?;
    }
    writeln!(w)?;

    Ok(())
}

/// Write a VMD scene script that loads PSF + trajectory and sets radii.
///
/// Run with: `vmd -e scene.tcl`
pub fn write_vmd_script(
    path: &Path,
    topology: &Topology,
    psf_file: &str,
    trajectory_file: &str,
) -> anyhow::Result<()> {
    let file = std::fs::File::create(path)
        .with_context(|| format!("Cannot create '{}'", path.display()))?;
    let mut w = BufWriter::new(file);

    let traj_ext = Path::new(trajectory_file)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("xyz");

    let script_name = path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("scene.tcl");
    writeln!(w, "# Generated by Faunus — run with: vmd -e {script_name}")?;
    writeln!(w, "mol load psf {psf_file} {traj_ext} {trajectory_file}")?;
    writeln!(w, "mol modstyle 0 top VDW 1.0 12.0")?;
    writeln!(w, "pbc box")?;

    for atom in topology.atomkinds() {
        if let Some(sigma) = atom.sigma() {
            let typ = atom.name();
            writeln!(
                w,
                "set sel [atomselect top \"type {typ}\"]; $sel set radius {:.4}; $sel delete",
                sigma / 2.0,
            )?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::group::Group;

    fn test_topology(name: &str, yaml: &str) -> crate::topology::Topology {
        let dir = std::env::temp_dir();
        let yaml_path = dir.join(format!("faunus_test_psf_{name}.yaml"));
        std::fs::write(&yaml_path, yaml).unwrap();
        let topology = crate::topology::Topology::from_file(&yaml_path).unwrap();
        std::fs::remove_file(&yaml_path).ok();
        topology
    }

    #[test]
    fn write_minimal_psf() {
        let topology = test_topology(
            "minimal",
            r#"
atoms:
  - name: LJ
    mass: 1.0
    charge: 0.5
molecules:
  - name: colloid
    atoms: [LJ, LJ]
    bonds:
      - index: [0, 1]
system:
  blocks:
    - {molecule: colloid, N: 2}
  cell: !Cuboid [10.0, 10.0, 10.0]
"#,
        );

        let dir = std::env::temp_dir();
        let path = dir.join("faunus_test_minimal.psf");
        let groups = vec![Group::new(0, 0, 0..2), Group::new(1, 0, 2..4)];

        write_psf(&path, &topology, &groups).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        std::fs::remove_file(&path).ok();

        assert!(content.contains("PSF EXT"));
        assert!(content.contains("!NATOM"));
        assert!(content.contains("!NBOND"));
        assert!(content.contains("         4 !NATOM"));
        assert!(content.contains("         2 !NBOND"));
    }

    #[test]
    fn write_vmd_scene_script() {
        let topology = test_topology(
            "vmd",
            r#"
atoms:
  - {name: A, mass: 1.0, sigma: 4.0}
  - {name: B, mass: 2.0}
molecules:
  - name: M
    atoms: [A, B]
system:
  blocks:
    - {molecule: M, N: 1}
  cell: !Cuboid [10.0, 10.0, 10.0]
"#,
        );

        let dir = std::env::temp_dir();
        let tcl_path = dir.join("faunus_test_vmd.tcl");

        write_vmd_script(&tcl_path, &topology, "traj.psf", "traj.xtc").unwrap();
        let content = std::fs::read_to_string(&tcl_path).unwrap();
        std::fs::remove_file(&tcl_path).ok();

        assert!(content.contains("mol load psf traj.psf xtc traj.xtc"));
        assert!(content.contains("pbc box"));
        // A has sigma=4.0, so radius=2.0
        assert!(content.contains("type A"));
        assert!(content.contains("2.0000"));
        // B has no sigma — should not appear
        assert!(!content.contains("type B"));
    }

    #[test]
    fn resid_per_group_not_per_atom() {
        let topology = test_topology(
            "resid",
            r#"
atoms:
  - name: X
    mass: 1.0
molecules:
  - name: dimer
    atoms: [X, X]
system:
  blocks:
    - {molecule: dimer, N: 2}
  cell: !Cuboid [10.0, 10.0, 10.0]
"#,
        );

        let dir = std::env::temp_dir();
        let path = dir.join("faunus_test_resid.psf");
        let groups = vec![Group::new(0, 0, 0..2), Group::new(1, 0, 2..4)];

        write_psf(&path, &topology, &groups).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        std::fs::remove_file(&path).ok();

        // Both atoms of first dimer should share resid 1,
        // both atoms of second dimer should share resid 2
        let atom_lines: Vec<&str> = content
            .lines()
            .skip_while(|l| !l.contains("!NATOM"))
            .skip(1)
            .take(4)
            .collect();
        assert_eq!(atom_lines.len(), 4);
        // Extract resid field (second 8-char field after 10-char index + space + 8-char segment + space)
        fn resid(line: &str) -> &str {
            line.split_whitespace().nth(2).unwrap()
        }
        assert_eq!(resid(atom_lines[0]), "1");
        assert_eq!(resid(atom_lines[1]), "1");
        assert_eq!(resid(atom_lines[2]), "2");
        assert_eq!(resid(atom_lines[3]), "2");
    }
}
